:experimental:
  # Enable/disable foreman commands
  :enable_module: true

  # Enable condensed help, highly experimental
  :enable_help: false

  # Enable config command
  :enable_config_command: false

  # Enable fuzzy matching of subcommands
  :enable_fuzzy_subcommands: false

  # Enable full-help command
  :enable_full_help_command: false
